### ISSUE TITLE
[ Issue ] Responsive Design Issue 

### ISSUE THREAD

**Issue by 9munnawar9** [codeforpakistan/watchtower-web#12]
When opening the application on an Android device using Google Chrome, some buttons and text elements are partially cut off, making them difficult to read. This issue occurs in portrait mode. However, when the device is rotated to landscape mode, the layout adjusts correctly, and the content displays as expected.

![after rotate](https://github.com/user-attachments/assets/abb316e7-9146-4ac5-92cb-713955c90bd3)
![Before rotat](https://github.com/user-attachments/assets/3c6e8bdf-f7d2-4a7e-967b-c5496c8c2df3)

**Comment by aliirz** [comment]
#13 fixes this
